version: "4.12.0"

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: vial
      POSTGRES_PASSWORD: vial
      POSTGRES_DB: vial
    ports:
      - 5432:5432
  # Node Server
  nodeserver:
    image: node:18.15.0
    command: node ./app.js
    working_dir: /src
    volumes:
      - ./server:/src
    environment:
      DATABASE_URL: postgres://vial:vial@database:5432/vial
    ports:
      - 5001:5001
  # React Client
  client:
    image: node:18.15.0
    command: yarn start
    working_dir: /src
    volumes:
      - ./client:/src
    environment:
      POSTGRES_USER: vial
      POSTGRES_PASSWORD: vial
      POSTGRES_DB: vial
    ports:
      - 3000:3000